### ISSUE TITLE
[BUG] Possible bug in how a summing matrix is created

### ISSUE THREAD

**Issue by wilfreddesert** [carlomazzaferro/scikit-hts#78]
https://github.com/carlomazzaferro/scikit-hts/blob/b9615b1c65c590449d27eced7b8a43fd16cea59a/hts/functions.py#L65

@carlomazzaferro , it seems that there might be problems with this function. 
For example, when working with `data = load_mobility_data()`, there is the `OTHER` category that consists of several bottom-level series, but the rule that is coded (each part of the larger series is part of the bottom level when split by `_` or `-` (by the way, I think there must be a more strict convention here) doesn't apply here. 

Here's the hierarchy tree:

```
{'total': ['CH', 'SLU', 'BT', 'OTHER'],
 'CH': ['CH_07', 'CH_02', 'CH_08', 'CH_05', 'CH_01'],
 'SLU': ['SLU_15', 'SLU_01', 'SLU_19', 'SLU_07', 'SLU_02'],
 'BT': ['BT_01', 'BT_03'],
 'OTHER': ['WF_01', 'CBD_13']}
 ```
 
 As you can see, that function will create a wrong summing matrix in this scenario. Or am I missing anything?

**Comment by carlomazzaferro** [comment]
Maybe @noahsa (the person that implemented that specific functionality) can pitch in?

**Comment by noahsa** [comment]
Yes, the OTHER category will not work in the current approach. It is unfortunate that this breaks the mobility example. I have not had the chance to go back and fix it. I tried to specify [here](https://scikit-hts.readthedocs.io/en/latest/hierarchy.html) the data/ string requirements. For this example to work OTHER would have to be formatted as ```"OTHER": ["OTHER_01",  "OTHER_13"]```. 

The reason these constraints exist on the strings is to make it easier to create the summing matrix for grouped time series. When the strings are formatted this way it makes it trivial to search them to find out what groups each level belongs to because the string contains all the information. Hence, breaking the mobility example when OTHER, WF and CBD don't match.

I hope this helps! Please let me know if you any clarifying questions
